name: Deploy OpenRemote
on: 
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  connect-with-federated-credential:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - name: Connect to Azure
        uses: Azure/login@v2.2.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
      - name: List Resource Groups
        uses: Azure/powershell@v2
        with:
          azPSVersion: latest
          inlineScript: |
            Get-AzResourceGroup | ft
