name: Deploy OpenRemote
on:
  workflow_dispatch:
    inputs:
      customer_name:
        description: 'Customer name'
        required: true
        default: 'openremote'
        type: string
      enable_backups:
        description: 'Enable backups'
        required: true
        default: false
        type: boolean
      enable_monitoring:
        description: 'Enable monitoring'
        required: true
        default: false
        type: boolean
      region:
        description: 'Azure region'
        required: true
        default: 'Central India'
        type: string
      email:
        description: 'Email address for metric alerts'
        required: true
        default: ''

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    environment: Development

    defaults:
      run:
        shell: bash
        working-directory: ./terraform-azure

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ./
          framework: terraform
        continue-on-error: true
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: "1.8.5"

      - name: Connect to Azure
        uses: Azure/login@v2.2.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Ensure Resource Group, Storage Account and Container Exist
        run: |
          RESOURCE_GROUP_NAME="${{ github.event.inputs.customer_name }}-rg"
          STORAGE_ACCOUNT="${{ github.event.inputs.customer_name }}storage"
          CONTAINER_NAME="${{ github.event.inputs.customer_name }}container"
          
          echo "RESOURCE_GROUP_NAME=$RESOURCE_GROUP_NAME"
          echo "STORAGE_ACCOUNT=$STORAGE_ACCOUNT"
          echo "CONTAINER_NAME=$CONTAINER_NAME"

          # Create resource group if it doesn't exist
          az group show --name $RESOURCE_GROUP_NAME || \
          az group create --name $RESOURCE_GROUP_NAME --location ${{ github.event.inputs.region }}
        
          # Create storage account if it doesn't exist
          az storage account show --name $STORAGE_ACCOUNT --resource-group $RESOURCE_GROUP_NAME || \
          az storage account create --name $STORAGE_ACCOUNT --resource-group $RESOURCE_GROUP_NAME --location ${{ github.event.inputs.region }} --sku Standard_LRS
        
          # Create storage container if it doesn't exist
          az storage container show --name $CONTAINER_NAME --account-name $STORAGE_ACCOUNT --auth-mode login || \
          az storage container create --name $CONTAINER_NAME --account-name $STORAGE_ACCOUNT --auth-mode login
          
      - name: Terraform Init
        id: init
        env:
          STORAGE_ACCOUNT: ${{ github.event.inputs.customer_name }}storage
          CONTAINER_NAME: ${{ github.event.inputs.customer_name }}container
          RESOURCE_GROUP_NAME: ${{ github.event.inputs.customer_name }}-rg
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: terraform init -backend-config="storage_account_name=$STORAGE_ACCOUNT" -backend-config="container_name=$CONTAINER_NAME" -backend-config="resource_group_name=$RESOURCE_GROUP_NAME"

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
        
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        
      - name: Terraform Plan
        id: plan
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          TF_VAR_customer_name: ${{ github.event.inputs.customer_name }}
          TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          TF_VAR_ssh_source_ip: ${{ secrets.SSH_SOURCE_IP }}
          TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
          TF_VAR_enable_backups: ${{ github.event.inputs.enable_backups }}
          TF_VAR_enable_monitoring: ${{ github.event.inputs.enable_monitoring }}
          TF_VAR_region: ${{ github.event.inputs.region }}
          TF_VAR_alert_email_address: ${{ github.event.inputs.email }}   
        run: terraform plan -no-color
        continue-on-error: true
      
      - name: Terraform Apply
        id: apply
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          TF_VAR_customer_name: ${{ github.event.inputs.customer_name }}
          TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          TF_VAR_ssh_source_ip: ${{ secrets.SSH_SOURCE_IP }}
          TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
          TF_VAR_enable_backups: ${{ github.event.inputs.enable_backups }}
          TF_VAR_enable_monitoring: ${{ github.event.inputs.enable_monitoring }}
          TF_VAR_region: ${{ github.event.inputs.region }}
          TF_VAR_alert_email_address: ${{ github.event.inputs.email }}
        run: terraform apply -no-color -auto-approve
        continue-on-error: true